server:
  port: 8081
  servlet:
    context-path: /api/v1.0

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/content_pub_db?useSSL=false&createDatabaseIfNotExist=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Colombo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate
    show-sql: true

  # Kafka Producer properties
  kafka:
    producer:
      bootstrap-servers: host.docker.internal:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      compression-type: lz4

# Notification configs.
messaging:
  is-enabled: true
  topic-names:
    notification: test.topic.notify

view:
  content-list:
    page-size:
      max: 50 # maximum allowed page size for view API